---
monitoring_instance: Ich
scrape_interval: 30s

jobs:
  - CoreInfra:
          job_name: Infra
          scrape_interval: 30s
          static_config:
          targets:
            - target1:
                ip: 192.168.178.2
            - target2:
                ip: 192.168.178.3
            - target3:
                ip: 191.168.178.4
